# Generated by Django 3.1.3 on 2023-02-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='')),
                ('tipo_platillo', models.TextField(default='')),
                ('calorias', models.FloatField(default=0)),
                ('proteinas', models.FloatField(default=0)),
                ('pais_origen', models.TextField(default='')),
                ('ingredientes', models.TextField(default='')),
                ('saludable', models.TextField(default='Si')),
                ('tiempo_coccion', models.IntegerField(default=0)),
                ('dificultad_preparacion', models.PositiveSmallIntegerField(default=1)),
                ('utensilios_requeridos', models.TextField(default='')),
            ],
        ),
    ]
